# SPDX-FileCopyrightText: Timothée Ravier <tim@siosm.fr>
# SPDX-License-Identifier: CC0-1.0

name: "Build sysexts for Fedora"

env:
  GH_TOKEN: ${{ github.token }}
  RELEASEURL: "https://github.com/${{ github.repository }}/releases/download"

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:
    inputs:
      force-rebuild:
        description: 'Force rebuild of all sysexts'
        required: true
        default: false
        type: boolean

# Needed to allow creating a release
permissions:
  contents: write

# Prevent multiple workflow runs from racing to ensure that pushes are made
# sequentialy for the main branch. Also cancel in progress workflow runs.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build-fedora-44-x86_64:
    runs-on: "ubuntu-24.04"
    container:
      image: "ghcr.io/fedora-sysexts/buildroot:latest"
      options: "--privileged --security-opt label=disable --user 0:0"
    env:
      IMAGE: "quay.io/fedora-ostree-desktops/base-atomic:44"
      FORCE_REBUILD: ${{ inputs.force-rebuild }}
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v6

      - name: "Setup artifacts and dnf cache directories"
        run: |
          mkdir -p artifacts .dnf-cache

      - name: "Mark directory as safe"
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git fetch --no-tags --prune --depth=1 origin +refs/heads/main:refs/remotes/origin/main

      - name: "Build sysext: ivpn"
        uses: ./.github/actions/build
        with:
          sysext: 'ivpn'
          image: ${{ env.IMAGE }}

      - name: "Build sysext: libvirt-devel"
        uses: ./.github/actions/build
        with:
          sysext: 'libvirt-devel'
          image: ${{ env.IMAGE }}

      - name: "Build sysext: mpd"
        uses: ./.github/actions/build
        with:
          sysext: 'mpd'
          image: ${{ env.IMAGE }}

      - name: "Build sysext: qemu-user-static"
        uses: ./.github/actions/build
        with:
          sysext: 'qemu-user-static'
          image: ${{ env.IMAGE }}

      - name: "Build sysext: qemu"
        uses: ./.github/actions/build
        with:
          sysext: 'qemu'
          image: ${{ env.IMAGE }}

      - name: "Build sysext: rclone"
        uses: ./.github/actions/build
        with:
          sysext: 'rclone'
          image: ${{ env.IMAGE }}

  build-fedora-silverblue-44-x86_64:
    runs-on: "ubuntu-24.04"
    container:
      image: "ghcr.io/fedora-sysexts/buildroot:latest"
      options: "--privileged --security-opt label=disable --user 0:0"
    env:
      IMAGE: "quay.io/fedora-ostree-desktops/silverblue:44"
      FORCE_REBUILD: ${{ inputs.force-rebuild }}
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v6

      - name: "Setup artifacts and dnf cache directories"
        run: |
          mkdir -p artifacts .dnf-cache

      - name: "Mark directory as safe"
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git fetch --no-tags --prune --depth=1 origin +refs/heads/main:refs/remotes/origin/main

  build-fedora-kinoite-44-x86_64:
    runs-on: "ubuntu-24.04"
    container:
      image: "ghcr.io/fedora-sysexts/buildroot:latest"
      options: "--privileged --security-opt label=disable --user 0:0"
    env:
      IMAGE: "quay.io/fedora-ostree-desktops/kinoite:44"
      FORCE_REBUILD: ${{ inputs.force-rebuild }}
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v6

      - name: "Setup artifacts and dnf cache directories"
        run: |
          mkdir -p artifacts .dnf-cache

      - name: "Mark directory as safe"
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git fetch --no-tags --prune --depth=1 origin +refs/heads/main:refs/remotes/origin/main

  build-fedora-coreos-stable-x86_64:
    runs-on: "ubuntu-24.04"
    container:
      image: "ghcr.io/fedora-sysexts/buildroot:latest"
      options: "--privileged --security-opt label=disable --user 0:0"
    env:
      IMAGE: "quay.io/fedora/fedora-coreos:stable"
      FORCE_REBUILD: ${{ inputs.force-rebuild }}
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v6

      - name: "Setup artifacts and dnf cache directories"
        run: |
          mkdir -p artifacts .dnf-cache

      - name: "Mark directory as safe"
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git fetch --no-tags --prune --depth=1 origin +refs/heads/main:refs/remotes/origin/main

  build-fedora-coreos-next-x86_64:
    runs-on: "ubuntu-24.04"
    container:
      image: "ghcr.io/fedora-sysexts/buildroot:latest"
      options: "--privileged --security-opt label=disable --user 0:0"
    env:
      IMAGE: "quay.io/fedora/fedora-coreos:next"
      FORCE_REBUILD: ${{ inputs.force-rebuild }}
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v6

      - name: "Setup artifacts and dnf cache directories"
        run: |
          mkdir -p artifacts .dnf-cache

      - name: "Mark directory as safe"
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git fetch --no-tags --prune --depth=1 origin +refs/heads/main:refs/remotes/origin/main

  build-fedora-44-aarch64:
    runs-on: "ubuntu-24.04-arm"
    container:
      image: "ghcr.io/fedora-sysexts/buildroot:latest"
      options: "--privileged --security-opt label=disable --user 0:0"
    env:
      IMAGE: "quay.io/fedora-ostree-desktops/base-atomic:44"
      FORCE_REBUILD: ${{ inputs.force-rebuild }}
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v6

      - name: "Setup artifacts and dnf cache directories"
        run: |
          mkdir -p artifacts .dnf-cache

      - name: "Mark directory as safe"
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git fetch --no-tags --prune --depth=1 origin +refs/heads/main:refs/remotes/origin/main

      - name: "Build sysext: ivpn"
        uses: ./.github/actions/build
        with:
          sysext: 'ivpn'
          image: ${{ env.IMAGE }}

      - name: "Build sysext: libvirt-devel"
        uses: ./.github/actions/build
        with:
          sysext: 'libvirt-devel'
          image: ${{ env.IMAGE }}

      - name: "Build sysext: mpd"
        uses: ./.github/actions/build
        with:
          sysext: 'mpd'
          image: ${{ env.IMAGE }}

      - name: "Build sysext: qemu-user-static"
        uses: ./.github/actions/build
        with:
          sysext: 'qemu-user-static'
          image: ${{ env.IMAGE }}

      - name: "Build sysext: qemu"
        uses: ./.github/actions/build
        with:
          sysext: 'qemu'
          image: ${{ env.IMAGE }}

      - name: "Build sysext: rclone"
        uses: ./.github/actions/build
        with:
          sysext: 'rclone'
          image: ${{ env.IMAGE }}

  build-fedora-silverblue-44-aarch64:
    runs-on: "ubuntu-24.04-arm"
    container:
      image: "ghcr.io/fedora-sysexts/buildroot:latest"
      options: "--privileged --security-opt label=disable --user 0:0"
    env:
      IMAGE: "quay.io/fedora-ostree-desktops/silverblue:44"
      FORCE_REBUILD: ${{ inputs.force-rebuild }}
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v6

      - name: "Setup artifacts and dnf cache directories"
        run: |
          mkdir -p artifacts .dnf-cache

      - name: "Mark directory as safe"
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git fetch --no-tags --prune --depth=1 origin +refs/heads/main:refs/remotes/origin/main

  build-fedora-kinoite-44-aarch64:
    runs-on: "ubuntu-24.04-arm"
    container:
      image: "ghcr.io/fedora-sysexts/buildroot:latest"
      options: "--privileged --security-opt label=disable --user 0:0"
    env:
      IMAGE: "quay.io/fedora-ostree-desktops/kinoite:44"
      FORCE_REBUILD: ${{ inputs.force-rebuild }}
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v6

      - name: "Setup artifacts and dnf cache directories"
        run: |
          mkdir -p artifacts .dnf-cache

      - name: "Mark directory as safe"
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git fetch --no-tags --prune --depth=1 origin +refs/heads/main:refs/remotes/origin/main

  build-fedora-coreos-stable-aarch64:
    runs-on: "ubuntu-24.04-arm"
    container:
      image: "ghcr.io/fedora-sysexts/buildroot:latest"
      options: "--privileged --security-opt label=disable --user 0:0"
    env:
      IMAGE: "quay.io/fedora/fedora-coreos:stable"
      FORCE_REBUILD: ${{ inputs.force-rebuild }}
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v6

      - name: "Setup artifacts and dnf cache directories"
        run: |
          mkdir -p artifacts .dnf-cache

      - name: "Mark directory as safe"
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git fetch --no-tags --prune --depth=1 origin +refs/heads/main:refs/remotes/origin/main

  build-fedora-coreos-next-aarch64:
    runs-on: "ubuntu-24.04-arm"
    container:
      image: "ghcr.io/fedora-sysexts/buildroot:latest"
      options: "--privileged --security-opt label=disable --user 0:0"
    env:
      IMAGE: "quay.io/fedora/fedora-coreos:next"
      FORCE_REBUILD: ${{ inputs.force-rebuild }}
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v6

      - name: "Setup artifacts and dnf cache directories"
        run: |
          mkdir -p artifacts .dnf-cache

      - name: "Mark directory as safe"
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git fetch --no-tags --prune --depth=1 origin +refs/heads/main:refs/remotes/origin/main

  publish-sysexts:
    runs-on: "ubuntu-24.04"
    container:
      image: "ghcr.io/fedora-sysexts/buildroot:latest"
      options: "--privileged --security-opt label=disable --user 0:0"
    # Run after the builds and versionned release
    needs:
      - build-fedora-43-x86_64
      - build-fedora-43-aarch64
      - build-fedora-44-x86_64
      - build-fedora-44-aarch64
      - build-fedora-silverblue-43-x86_64
      - build-fedora-silverblue-43-aarch64
      - build-fedora-silverblue-44-x86_64
      - build-fedora-silverblue-44-aarch64
      - build-fedora-kinoite-43-x86_64
      - build-fedora-kinoite-43-aarch64
      - build-fedora-kinoite-44-x86_64
      - build-fedora-kinoite-44-aarch64
      - build-fedora-coreos-stable-x86_64
      - build-fedora-coreos-stable-aarch64
      - build-fedora-coreos-next-x86_64
      - build-fedora-coreos-next-aarch64
    # Use `always()` to still run if any dependent job fails
    if: ${{ always() && (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main' }}
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v6

      - name: "Mark directory as safe"
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git fetch --no-tags --prune --depth=1 origin +refs/heads/main:refs/remotes/origin/main

      - name: "Gather all sysexts releases"
        uses: ./.github/actions/gather
